const MatchCardsData = [
    {
        team1: "AUS-W",
        team1Flag: "/public/assets/australia.png",
        score1: "298/6",
        team2: "IND-W",
        team2Flag: "/public/assets/india.png",
        score2: "215",
        overs: "(45.1/50 ov, target 299)",
    },
    {
        team1: "CFC",
        team1Flag: "public/assets/australia.png",
        score1: "1",
        team2: "HYD",
        team2Flag: "/public/assets/india.png",
        score2: "0",
        overs: "",
    },
    {
        team1: "ATA",
        team1Flag: "public/assets/australia.png",
        score1: "2",
        team2: "RMA",
        team2Flag: "/public/assets/india.png",
        score2: "3",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },
    {
        team1: "SHK",
        team1Flag: "public/assets/australia.png",
        score1: "0",
        team2: "MUN",
        team2Flag: "/public/assets/india.png",
        score2: "5",
        overs: "",
    },

    // Add more matches...
];

export default MatchCardsData;
